window.CLINES_PROJECT_OPTIONS = {
  dealers: [
    "11400",
    "A City Discount/PeachTrader",
    "Aiken-Augusta Equipment",
    "All State Rest Equip (Auburn, AL)",
    "All-State Restaurant Eqipment Co.",
    "American Kitchen Equipment",
    "Atlanta Equipment Co",
    "Atlanta H&R",
    "Atlanta Restaurant Equipment",
    "Atlas Restaurant Supply",
    "Baring",
    "Beltram (SC Division)",
    "Berlins Restaurant Equipment (now Culinex) (See Krowne tab)",
    "Big A Distributors",
    "Blue Ridge Restaurant Equipment",
    "Boelter",
    "Boelter-Direct South",
    "Bresco",
    "Brightside",
    "C&T Design",
    "Cape Fear",
    "Carolina Cooks",
    "Carolina Restaurant Supply",
    "Cary Restaurant Equipment",
    "CCSE",
    "Central Restaurant Products",
    "Chef's Deal",
    "CKR Augusta",
    "Clark Foodservice Equipment",
    "Commercial Refrigeration",
    "County Line Restaurant Equipment",
    "Culinary Depot",
    "Culinary Depot - ATL",
    "Deacon Foodservice Solutions",
    "Denver Equipment Co.",
    "Dietary Equipment Co.",
    "Douglas Equipment",
    "Dykes",
    "Eastern",
    "EC Rest Equip",
    "Edward Don",
    "Edward Don (PO Ending in 50)",
    "Edward Don (PO Ending in 70)",
    "Equipment Plus Foodservice",
    "Farriss Hospitality",
    "FKG Equipment",
    "Food Equipment Co",
    "Food Equipment Co.",
    "Food Service Supply Int'l Inc.",
    "Fortuna",
    "Franke Foodservice",
    "FRS (All Branches)",
    "GFS",
    "Government Sales LLC",
    "Great Lakes",
    "Great Lakes - ATL",
    "Hardwick's",
    "Hawk",
    "HM Fixture",
    "Hooks Consulting",
    "IFG (FSR) formerly Big A Dist.",
    "Innovative Foodservice Group (IFG)(Formerly JES)",
    "Island Restaurant Equipment & Design",
    "Jacobi Lewis Co.- Greensboro, NC",
    "Jacobi Lewis Co.-Wilmington, NC",
    "JES",
    "Jett's BBQ & Equipment Sales",
    "John The Greek Restaurant Equip",
    "Johnson Lancaser - ATL",
    "Johnson-Lancaster",
    "JXT Company",
    "Kamran / Culinex (Use quotes@kamranco.com when sending out quotes)",
    "KaTom",
    "Kesco",
    "Lance Restaurant Supply",
    "Littco",
    "Lowcountry Restaurant Equipment",
    "Manning Bros",
    "Metro Chef",
    "Mobile Fixture (AL & FL)",
    "Mobile Fixture (Atlanta)",
    "Mobile Fixture (Columbus)",
    "Mobile Fixture (TN)",
    "New Retro Dining",
    "Norvell",
    "Owens Equipment",
    "Performance Foodservice",
    "Price Refrigeration & Restaurant Eq.",
    "Price-Davis Inc.",
    "Prime Ticket Inc.",
    "ProKitchen, LLC",
    "RaceTrac Petroleum Inc.",
    "Raleigh Restaurant Equipment",
    "Rapids Foodservice Contract",
    "RECO Savannah",
    "Reinhart Foodservice=Performance",
    "Rest Equip Market",
    "Rest Equip Savannah",
    "Rest Solutions",
    "Restaurant Depot",
    "Restaurant Discount Store",
    "Restaurant Equipment Co of Bluffton (Savannah)",
    "Restaurant Equipment Warehouse",
    "Sanford",
    "Singer H&R",
    "Singer T & L (Norcross Office)",
    "Singer T&L (28305)",
    "Sodexo (Formerly Centerplate)",
    "Southeasst Fixtures",
    "Stafford Smith",
    "Stallings Refrigeration",
    "Supplies on the Fly - SYSCO",
    "Supreme",
    "Sysco",
    "Ta Tung",
    "Taylor Group",
    "Thomas Equipment",
    "Tillman's",
    "Tongnan Fa",
    "Total Resa",
    "TrendCo",
    "TriMark Foodcraft",
    "TriMark Strategic",
    "Underwood RSE",
    "United Restaurant Supply (URECO)",
    "US Foods",
    "USA Equip Direct",
    "Verticle Culinary Solutions LLS (Formerly General Sales)",
    "Wasserstrom",
    "Wasserstrom Co.",
    "Willingham",
    "Windrock (Conv Str chain Dist) bought by Chicagoland"
  ],
  estimators: [
    "Brad Ross", "Brandy Solonka", "Chris Brewer", "David Oxman", "Davy Phillips", "Geoff Winn",
    "Janet Mitchell", "Jessica Lott", "Josh Myers", "Kristen Nygard", "Lorin Pirani", "Mark Turner",
    "Paul Remoll", "Rain Biggerman", "Reina Sibrian", "Suzy O'Connel", "Tiffany Elliot", "Warren Goldsmith"
  ],
  salesReps: [
    "Brad Ross", "Brandy Solonka", "Chris Brewer", "David Oxman", "Davy Phillips", "Geoff Winn",
    "Janet Mitchell", "Jessica Lott", "Josh Myers", "Lorin Pirani", "Mark Turner", "Paul Remoll",
    "Tiffany Elliot", "Warren Goldsmith"
  ]
};
